events {}
http {
    server {
        listen 80;
        location / {
            proxy_pass http://simple-http:8080;
            proxy_set_header X-Real-IP $http_x_real_ip;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }
    }
}
